// JavaScript Document
document.write('<div class="w">');
document.write('<div class="bottom_t_logo">');
document.write('<img src="images/u188.png" alt="logo">');
document.write('</div>');
document.write('<div class="lj">');
document.write('<ul>');
document.write('<li class="set_font"><a href="javascript:;">国内</a></li>');
document.write('<li><a href="javascript:;">新疆</a></li>');
document.write('<li><a href="javascript:;">纺织</a></li>');
document.write('<li><a href="javascript:;">棉副</a></li>');
document.write('<li><a href="javascript:;">图片</a></li>');
document.write('</ul>');
document.write('<ul>');
document.write('<li class="set_font"><a href="javascript:;">国际</a></li>');
document.write('<li><a href="javascript:;">CNCE</a></li>');
document.write('<li><a href="javascript:;">报告</a></li>');
document.write('<li><a href="javascript:;">期货</a></li>');
document.write('<li><a href="javascript:;">视频</a></li>');
document.write('</ul>');
document.write('<ul>');
document.write('<li class="set_font"><a href="javascript:;">价格</a></li>');
document.write('<li><a href="javascript:;">数字能言</a></li>');
document.write('<li><a href="javascript:;"></a></li>');
document.write('<li class="set_font"><a href="javascript:;">统计</a></li>');
document.write('<li><a href="javascript:;">交易行情</a></li>');
document.write('</ul>');
document.write('<ul>');
document.write('<li class="set_font"><a href="javascript:;">疆棉竞卖</a></li>');
document.write('<li><a href="javascript:;">运输补贴</a></li>');
document.write('<li><a href="javascript:;"></a></li>');
document.write('<li class="set_font"><a href="javascript:;">现货挂牌</a></li>');
document.write('<li><a href="javascript:;">业务专栏</a></li>');
document.write('</ul>');
document.write('<ul>');
document.write('<li class="set_font"><a href="javascript:;">更新列表</a></li>');
document.write('<li><a href="javascript:;">商桥</a></li>');
document.write('<li><a href="javascript:;">贵宾专区</a></li>');
document.write('<li><a href="javascript:;">产品服务</a></li>');
document.write('<li><a href="javascript:;">信息采集</a></li>');
document.write('<li><a href="javascript:;">指数介绍</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('<div class="address">');
document.write('<div class="cf"><i class="iph"></i><span>010-88086622</span></div>');
document.write('<div class="cf"><i class="email"></i><span>info@cottonchina.org</span></div>');
document.write('<div class="cf l_h"><i class="coordinate"></i><span>北京市西城区宣武门外大街甲1号环球财讯中心A5</span></div>');
document.write('<div class="find_s">');
document.write('<form>')
document.write('<input type="text" value="输入关键字" onfocus="if(value==\'输入关键字\') {value=\'\';this.style.color=\'#333333\'}" onblur="if (value==\'\') {value=\'输入关键字\';this.style.color=\'#999999\'}">');
document.write('<button><i class="find"></i></button>');
document.write('<form>')
document.write('</div>');
document.write('</div>');
document.write('</div>');